%Andrew Brown Homework 2 Problem 3

clc
clear
clf

%Phyisics of a harmful fall on different planets.

%Part A: What is the energy that is generated by a 10-meter fall for a 120
%pounds heavy object on the surface of Earth?

%Define given constants
massPounds=120; %mass in pounds
massKg=massPounds/2.246; %mass in kilograms
g=9.8; %acceleration due to gravity on earth
h=10; %height off the ground in meters

%Given equation
E=massKg*g*h; %energy generated from the fall in joules

%Print out the energy given off
fprintf('Energy from a 10m fall on Earth: %0.2f Joules\n', E)

%Part B: Choose three different planets of your choice, plot the energy
%generated by the fall of a 120 pounds object over the surface of each
%of Earth and the other planets. Your plot should show the energy 
%generated between values between 0 to 50 meters.
%and
%Part C: Identify on your graph and command window the harmful heights
%that will generate the same energy as a 10-meter fall on earth. 

%Define given constants
massPounds=120; %mass in pounds
massKg=massPounds/2.246; %mass in kilograms
g=[9.8, 26.0, 3.61, 3.75]; %accelerations due to gravity in m/s^2
h=linspace(0,50,100); %height off the ground in meters

%Given equations separated by planet
EEarth=massKg*g(1)*h; %energy generated from the fall in joules on earth
EJupiter=massKg*g(2)*h; %energy generated from the fall in joules on jupiter
EMercury=massKg*g(3)*h; %energy generated from the fall in joules on mercury
EMars=massKg*g(4)*h; %energy generated from the fall in joules on mars

%Plotting the graph for energy generated from a fall on Earth
subplot(2,2,1)
plot(h,EEarth)
title('Self-Check: Energy Generated from a fall on Earth')
xlabel('Height (m)')
ylabel('Energy (J)')
legend('Energy')
axis([0,50,0,3*10^4])



%Plotting the graph for energy generated from a fall on Jupiter
subplot(2,2,2)
plot(h,EJupiter)
title('Self-Check: Energy Generated from a fall on Jupiter')
xlabel('Height (m)')
ylabel('Energy (J)')
axis([0,50,0,7*10^4])

%Calculate and plot the point of a drop equivalent to a 10m drop on earth
hold on
JupiterHeight=E/(g(2)*massKg);
plot(JupiterHeight,E,'r*')
legend('Energy', 'Equivalent of 10m drop on Earth')



%Plotting the graph for energy generated from a fall on Mercury
subplot(2,2,3)
plot(h,EMercury)
title('Self-Check: Energy Generated from a fall on Mercury')
xlabel('Height (m)')
ylabel('Energy (J)')
axis([0,50,0,12*10^3])

%Calculate and plot the point of a drop equivalent to a 10m drop on earth
hold on
MercuryHeight=E/(g(3)*massKg);
plot(MercuryHeight,E,'r*')
legend('Energy', 'Equivalent of 10m drop on Earth')



%Plotting the graph for energy generated from a fall on Mars
subplot(2,2,4)
plot(h,EMars)
title('Self-Check: Energy Generated from a fall on Mars')
xlabel('Height (m)')
ylabel('Energy (J)')
axis([0,50,0,12*10^3])

%Calculate and plot the point of a drop equivalent to a 10m drop on earth
hold on
MarsHeight=E/(g(4)*massKg);
plot(MarsHeight,E,'r*')
legend('Energy', 'Equivalent of 10m drop on Earth')

%Print out the equivalent falls.
fprintf('The energy-equivalent fall to a 10m drop on Earth:\n Jupiter: %0.2fm\n Mercury: %0.2fm\n Mars: %0.2fm\n',JupiterHeight,MercuryHeight,MarsHeight)



